
services:
  wazuh.manager:
    build: .
    container_name: wazuh_manager
    hostname: wazuh-manager
    volumes:
      - ./manager:/entry
      - queue_vd:/var/ossec/queue/vd
      - queue_vd_updater:/var/ossec/queue/vd_updater
      - manager_logs:/var/ossec/logs
    command:
      - /entry/entrypoint.sh
    ports:
      - "1514:1514"
      - "1515:1515"
# Ubuntu agents
  ubuntu_jammy_agent:
    build: jammy_agent/
    container_name: ubuntu_jammy_agent
    hostname: ubuntu_jammy_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_jammy:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh

  ubuntu_focal_agent:
    build: focal_agent/
    container_name: ubuntu_focal_agent
    hostname: ubuntu_focal_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_focal:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh

  ubuntu_noble_agent:
    build: noble_agent/
    container_name: ubuntu_noble_agent
    hostname: ubuntu_noble_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_noble:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh

  ubuntu_bionic_agent:
    build: bionic_agent/
    container_name: ubuntu_bionic_agent
    hostname: ubuntu_bionic_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_bionic:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh
# Debian agents
  debian_buster_agent:
    build: buster_agent/
    container_name: debian_buster_agent
    hostname: debian_buster_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_buster:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh

  debian_bullseye_agent:
    build: bullseye_agent/
    container_name: debian_bullseye_agent
    hostname: debian_bullseye_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_bullseye:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh

  debian_bookworm_agent:
    build: bookworm_agent/
    container_name: debian_bookworm_agent
    hostname: debian_bookworm_agent
    volumes:
      - ./agent_files:/agent_files
      - etc_bookworm:/var/ossec/etc
    depends_on:
      - wazuh.manager
    command:
      - /agent_files/entrypoint.sh

volumes:
  queue_vd:
  queue_vd_updater:
  etc_jammy:
  etc_focal:
  etc_noble:
  etc_bionic:
  etc_buster:
  etc_bullseye:
  etc_bookworm:
  manager_logs:
