[cveDict]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/cve.sqlite3"

[ovalDict]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/oval.sqlite3"

[gost]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/gost.sqlite3"

[exploit]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/go-exploitdb.sqlite3"

[metasploit]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/go-msfdb.sqlite3"

[kevuln]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/go-kev.sqlite3"

[cti]
type = "sqlite3"
SQLite3Path = "/usr/local/bin/go-cti.sqlite3"

[servers]

[servers.ubuntu_jammy_agent]
host         = "ubuntu_jammy_agent"
port        ="22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]

[servers.ubuntu_focal_agent]
host         = "ubuntu_focal_agent"
port        = "22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]

[servers.ubuntu_noble_agent]
host         = "ubuntu_noble_agent"
port        = "22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]

[servers.ubuntu_bionic_agent]
host         = "ubuntu_bionic_agent"
port        = "22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]

[servers.debian_buster_agent]
host         = "debian_buster_agent"
port        = "22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]

[servers.debian_bullseye_agent]
host         = "debian_bullseye_agent"
port        = "22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]

[servers.debian_bookworm_agent]
host         = "debian_bookworm_agent"
port        = "22"
user        = "root"
keyPath     = "/root/.ssh/id_rsa"
scanMode     = ["fast"]
